name: Gaurab
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1-5" # afternoon 2:10 PM, Monday to Friday

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: maven build
        run: mvn install

      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v6
        with:
          name: vprofile-app
          path: target/*.war

      - name: notify if build fails
        if: failure()
        run: echo "build job failed! please check logs."

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: run tests on main branches
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "skipping unit tests and code analysis"
