name: Gaurab
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v222

      - name: maven build
        run: mvn install

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v6

      - name: run tests on main branches
        run: laura test

      - name: checkstyle
        run: mvn checkstyle:checkstyle
